spring:
 datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password: 
#    driver-class-name: org.mariadb.jdbc.Driver
#     url: jdbc:mariadb://127.0.0.1:3306/mydb 
#    username: root
#    password: 1234
